# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "debian/jessie64"

  config.vm.define "munin" do |sut|
    config.vm.network "private_network", ip: "10.0.1.10"
  end

  config.vm.define "app" do |sut|
    config.vm.network "private_network", ip: "10.0.1.20"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "site.yml"
    ansible.sudo = true

    ansible.groups = {
      "munin" => ["munin"],
      "app" => ["app"]
    }
  end
end
